services:
  orders_scala:
    image: postgres:13
    container_name: orders_scala
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5444:5432"
    volumes:
      - orders:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "orders"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  db_network:
    name: db_network

volumes:
  orders:
